DFF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout",)
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from .views import *

app_name = "main"
urlpatterns = [
    path('', views.showmain, name="showmain"),
    path('mentors/', views.showmentors, name="showmentors"),
    path('contact/', views.showcontact, name="showcontact"),
    path('recruit/', views.showrecruit, name="showrecruit"),
    path('dff/', views.showdff, name="showdff"),
    path('announce/', views.showannounce, name="showannounce"),
    path('message/', views.showmessage, name="showmessage"),
    path('dreamer/', views.showdreamer, name="showdreamer"),
    path('thanks/', views.showthanks, name="showthanks"),
    path('new/', views.showNew, name="showNew"),
    path('pwd/', views.showPwd, name="showPwd"),
    path('pwd_2/', views.showPwd_2, name="showPwd_2"),
    path('pwd_3/', views.showPwd_3, name="showPwd_3"),
    path('complete/', views.showcomplete, name="showcomplete"),
    path('create/', views.create, name="create"),
    path('delete/<str:id>', views.delete, name="delete"),
    path('message/<str:id>', views.showdetail, name="showdetail"),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    id = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=4, null=True)
    title = models.TextField(max_length=20)
    writer = models.CharField(max_length=20)
    pub_date = models.DateTimeField()
    body = models.TextField()

    def __str__(self):
        return self.writer

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth

def login(request):
    if request.method == 'POST':
        usr = request.POST['username']
        pwd = request.POST['password']
        user = auth.authenticate(request, username=usr, password=pwd)
        if user is not None:
            auth.login(request, user)
            return redirect('main:showmain')
        else:
            return render(request, 'login.html')
    elif request.method == 'GET':
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('main:showmain')
# Create your views here.

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.
def showmain(request):
    return render(request, 'main/mainpage.html')

def showmentors(request):
    return render(request, 'main/mentor_list.html')

def showcontact(request):
    return render(request, 'main/contact.html')

def showrecruit(request):
    return render(request, 'main/recruit.html')

def showdff(request):
    return render(request, 'main/dff.html')

def showannounce(request):
    return render(request, 'main/announce.html')

def showmessage(request):
    blogs = Blog.objects.all()

    p = Paginator(Blog.objects.order_by('-id'),10)
    page = request.GET.get('page')
    venues = p.get_page(page)
    return render(request, 'main/message.html',{'blogs':blogs, 'venues':venues})

def showdreamer(request):
    return render(request, 'main/dreamer.html')

def showthanks(request):
    return render(request, 'main/thanks.html')

def showNew(request):
    if request.method == "GET":
        return render(request, 'main/new.html')

def showcomplete(request):
    return render(request, 'main/complete.html')
        
def showPwd(request):
    return render(request, 'main/pwd.html') 

def showPwd_2(request):
    return render(request, 'main/pwd_2.html') 

def showPwd_3(request):
    return render(request, 'main/pwd_3.html') 

def showdetail(request, id):
    blog = get_object_or_404(Blog, pk=id)
    return render(request, 'main/detail.html', {'blog':blog})

def create(request):
    new_blog = Blog()
    new_blog.writer = request.POST['writer']
    new_blog.phone = request.POST['phone']
    new_blog.title = request.POST['title']
    new_blog.pub_date = timezone.now()
    new_blog.body = request.POST['body']
    new_blog.save()
    return redirect('main:showcomplete')

def delete(request, id):
    delete_blog = Blog.objects.get(id = id)
    delete_blog.delete()
    return redirect('main:showmessage')

# def test(request):
#     blog_list = Blog.objects.all()
#     page = request.Get.get('page', '1')
#     paginator = Paginator(blog_list,'10')
#     page_obj = paginator.page(page)
#     return render(request, 'main:showmessage', {'page_obj':page_obj})

# def showmessage(request):
#     blog_list = Blog.objects.all() #models.py Board 클래스의 모든 객체를 board_list에 담음
#     # board_list 페이징 처리
#     page = request.GET.get('page', '1') #GET 방식으로 정보를 받아오는 데이터
#     paginator = Paginator(blog_list, '10') #Paginator(분할될 객체, 페이지 당 담길 객체수)
#     page_obj = paginator.page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
#     return render(request, 'main:message.html', {'page_obj':page_obj}) 

DFF/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GGEWK9RBTG"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-GGEWK9RBTG');
    </script>

    <meta property="og:title" content="Dreamer">
    <meta property="og:url" content="dreamer.pe.kr">
    <meta property="og:description" content="Dream For Fresh에 오신 여러분 환영합니다 :)">
    <meta property="og:image" content="https://ifh.cc/g/CHSVWZ.png">
    <title>Dreamer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/js" href="{% static 'js/script.css' %}">
    <script type="text/javascript" src="script.js"></script>
</head>
<body>
    {% include 'shared/_navbar.html' %}
    
    <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>
</html>

DFF/templates/shared/_navbar.html
<nav class="navbar absolute-top" style="background-color: #F79400;">
    <div class="container-fluid ">
        <a class="navbar-brand " href="{% url 'main:showmain' %}">
            <!-- <img id="logo" src="https://i.ibb.co/ZTfbv3K/Dreamer-2.png"> -->
            <!-- <img id="logo" src="https://ifh.cc/g/8xZj2B.png"> -->
            <img id="logo" src="https://ifh.cc/g/hTRKvk.png">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    

        {% if user.is_authenticated %}
            <div class="offcanvas-header">
                <a id="logout" href="{% url 'accounts:logout' %}">멘토 로그아웃</a>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:showmain' %}">홈</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            드포프
                        </a>
                        <ul class="dropdown-menu dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:showPwd_3' %}">일정 안내</a></li>
                            <!-- <li><a class="dropdown-item" href="{% url 'main:showannounce' %}">공지</a></li> -->
                            <li><a class="dropdown-item" href="{% url 'main:showPwd' %}">감사한 여러분들께</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:showmessage' %}">수고한 멘토님들께</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            About Dreamer
                        </a>
                        <ul class="dropdown-menu dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:showmentors' %}">드리머 멘토 소개</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:showrecruit' %}">12기 모집 정보</a></li>
                        </ul>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a class="nav-link active">Contact</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="https://www.youtube.com/@user-jr3sr9em6k">
                            <img id="youtube_logo" src="https://ifh.cc/g/tgC1SS.png"/></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="https://www.instagram.com/dongguk_dreamer/">
                            <img id="insta_logo" src="https://ifh.cc/g/Vdr42W.png" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="https://blog.naver.com/donggukdreamer2012">
                            <img id="blog_logo" src="https://ifh.cc/g/ySc10H.png"/></a>
                    </li>
                </ul>
            </div>
            {% else %}
            <div class="offcanvas-header">
                <a id="login" href="{% url 'accounts:login' %}">멘토 로그인</a>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:showmain' %}">홈</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            드포프
                        </a>
                        <ul class="dropdown-menu dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:showPwd_3' %}">일정 안내</a></li>
                            <!-- <li><a class="dropdown-item" href="{% url 'main:showannounce' %}">공지</a></li> -->
                            <li><a class="dropdown-item" href="{% url 'main:showPwd' %}">감사한 여러분들께</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:showPwd_2' %}">수고한 멘토님들께</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            About Dreamer
                        </a>
                        <ul class="dropdown-menu dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:showmentors' %}">드리머 멘토 소개</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:showrecruit' %}">12기 모집 정보</a></li>
                        </ul>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a class="nav-link active">Contact</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="https://www.youtube.com/@user-jr3sr9em6k">
                            <img id="youtube_logo" src="https://ifh.cc/g/tgC1SS.png"/></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="https://www.instagram.com/dongguk_dreamer/">
                            <img id="insta_logo" src="https://ifh.cc/g/Vdr42W.png" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="https://blog.naver.com/donggukdreamer2012">
                            <img id="blog_logo" src="https://ifh.cc/g/ySc10H.png"/></a>
                        </li>
                </ul>
            </div>

            {% endif %}
            
            <li class="nav-item">
                <img id="by" src="https://ifh.cc/g/P0v4kY.png">
            </li>
        </div>
    </div>
</nav>

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="login">
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <img id="login_logo" src="https://ifh.cc/g/G9OT9L.png">
        <div id="id">
            <input type="text" id="input_id" name="username" placeholder="아이디"><br>
        </div>
        <div id="password">
            <input type="password" id="input_pwd" name="password" placeholder="비밀번호"><br>
        </div>  
        <input type="submit" id="login_button" value="로그인">
    </form>
</div>

{% endblock %}

main/templates/main/announce.html
{% extends 'base.html' %}

{% block content %}

<h1>공지</h1>

{% endblock %}

main/templates/main/complete.html
{% extends 'base.html' %}

{% block content %}

<img id="complete_1" src="https://ifh.cc/g/Qt5ODJ.jpg">
<img id="complete_2" src="https://ifh.cc/g/RzSVfR.jpg">

{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %}

{% block content %}

<h1>유튜브, 인스타, 블로그</h1>

{% endblock %}

main/templates/main/delete.html
{% extends 'base.html' %}

{% block content %}

<h1>메세지</h1>

<!-- {{blogs}} -->
<div>
    {% for blog in blogs %}
    <div>
        <h3>#{{blog.number}}</h3>
        <h3>{{blog.writer}}</h3>
        <h3>{{blog.body}}</h3>
    </div>
    <a href="{% url 'main:delete' %}">삭제하기</a>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="detail">
        <img id="letter_logo" src="https://ifh.cc/g/6z0hW3.png">
        <!-- <img id="letter_tem" src="https://ifh.cc/g/Q4QL0W.jpg"> -->
        <a id="detail_writer">{{blog.writer}} 님이 드리머 멘토님들께</a>
        <a id="detail_body">{{blog.body}}</a><br>
        <a id="detail_date">{{blog.pub_date}}</a>
</div>

{% endblock %}

main/templates/main/dff.html
{% extends 'base.html' %}

{% block content %}
<br>
<img id="schedule" src="https://ifh.cc/g/nAV8kh.jpg">
<div class="center_webex">
    <a href="https://dongguk.webex.com/meet/pr2022112026">
        <img id="center_webex" src="https://ifh.cc/g/9m6t4c.png">
    </a>
    <img id="center_activity_1" src="https://ifh.cc/g/TWTSZ3.jpg">
    <img id="center_activity_2" src="https://ifh.cc/g/FxzLr7.jpg">
</div>

<div class="team_webex">
    <a href="https://dongguk.webex.com/meet/pr2021112261">
        <img id="first_1" src="https://ifh.cc/g/NKmr1w.png" >
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021111160">
        <img id="first_1" src="https://ifh.cc/g/Jwal37.png">
    </a>    
    <a href="https://dongguk.webex.com/meet/pr2021111267">
        <img id="first_1" src="https://ifh.cc/g/hWMhfy.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021112127">    
        <img id="first_1" src="https://ifh.cc/g/8l9OcP.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021111945">
        <img id="first_1" src="https://ifh.cc/g/0YBNzk.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021110272">
        <img id="first_2" src="https://ifh.cc/g/AAyqMV.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2022110283">
        <img id="first_2" src="https://ifh.cc/g/dQVOhQ.png">
    </a>
    <a href="https://meet84.webex.com/meet/pr1824343077">
        <img id="first_2" src="https://ifh.cc/g/xKr2Xw.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2022113158">
        <img id="first_2" src="https://ifh.cc/g/Z2Dv4J.png">
    </a>
    <img id="group_activity_1" src="https://ifh.cc/g/zjCSOj.jpg">
    <img id="group_activity_2" src="https://ifh.cc/g/gzszo3.jpg">
    <br><br>

    <!-- <a href="https://dongguk.webex.com/meet/pr2021112261">
        <img id="first_1" src="https://ifh.cc/g/NKmr1w.png" >
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021111160">
        <img id="first_1" src="https://ifh.cc/g/Jwal37.png">
    </a>    
    <a href="https://dongguk.webex.com/meet/pr2021111267">
        <img id="first_1" src="https://ifh.cc/g/hWMhfy.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021112127">    
        <img id="first_1" src="https://ifh.cc/g/8l9OcP.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021111945">
        <img id="first_1" src="https://ifh.cc/g/0YBNzk.png"><br>
    </a>
    <a href="https://dongguk.webex.com/meet/pr2021110272">
        <img id="first_2" src="https://ifh.cc/g/AAyqMV.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2022110283">
        <img id="first_2" src="https://ifh.cc/g/dQVOhQ.png">
    </a>
    <a href="https://meet84.webex.com/meet/pr1824343077">
        <img id="first_2" src="https://ifh.cc/g/xKr2Xw.png">
    </a>
    <a href="https://dongguk.webex.com/meet/pr2022113158">
        <img id="first_2" src="https://ifh.cc/g/Z2Dv4J.png">
    </a> -->
</div>

{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <img id="welcome_1" src="https://ifh.cc/g/GXzHVD.jpg">
    <img id="welcome_2" src="https://ifh.cc/g/yNy5hC.jpg">
    <img id="site_description_1" src="https://ifh.cc/g/o11kCC.jpg">
    <img id="site_description_2" src="https://ifh.cc/g/YGzBny.jpg">
{% endblock %}

main/templates/main/message.html
<!-- 멘토에게 보이는 메세지 정리 -->
{% extends 'base.html' %}

{% block content %}

    <img id="arrive_letter" src="https://ifh.cc/g/RlX9MH.png">
    <a id="letter_ment">제목을 누르면 상세 내용을 볼 수 있어요!</a>

    <!-- {{blogs}} -->
    <div class="message">
        {% for blog in venues %}
        <div id="message">
            <!-- <script type="text/javascript">
                function modal()  {
                        location.href="{% url 'main:showdetail' id=blog.id %}"
                    }
            </script> -->
            <div id="message_content">
                <div id="blog_id">
                    <a id="blog_id">#{{blog.id}}</h3>
                </div>
                <!-- <a id="blog_writer">{{blog.writer}}</h3> -->
                <a id="blog_title" href="{% url 'main:showdetail' blog.id %}">{{blog.title}}</a>
                <!-- <a id="blog_body">{{blog.body}}</a> -->
            </div>
            <!-- <div id="blog_time">
                <a id="blog_time">{{blog.pub_date}}</a>
            </div> -->
            <div id="blog_delete">
                <a id="blog_delete" href="{% url 'main:delete' blog.id%}">삭제하기</a>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- 페이징처리 시작 -->
    <div id="paging">
        <ul class="pagination justify-content-center" style="margin-top: 2rem;">
            <!-- 이전페이지 -->
            {% if venues.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?&page={{ venues.previous_page_number }}">이전</a>
                <!-- href로 뎁스 설정 -->
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in venues.paginator.page_range %}
            {% if page_number >= venues.number|add:-5 and page_number <= venues.number|add:5 %}
            {% if page_number == venues.number %}
            <li class="page-item active bg-warning" aria-current="page">
                <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item bg-warning">
                <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?&page={{ page_obj.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <!-- 페이징처리 끝 -->

{% endblock %}

main/templates/main/new.html
<!-- 멘토에게 편지 작성 -->
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

<h1>메세지</h1>

<!-- {{blogs}} -->
<div>
    {% for blog in blogs %}
    <div>
        <h3>#{{blog.id}}</h3>
        <h3>{{blog.writer}}</h3>
        <h3>{{blog.body}}</h3>
    </div>
    <a href="{% url 'main:delete' blog.id%}">삭제하기</a>
    {% endfor %}
</div>

{% else %}

    <div class="form">
        <form action="{% url 'main:create' %}" method="post">
            {% csrf_token %}
            <img id="submit_logo" src="https://ifh.cc/g/4nwC9G.png"><br>
            <input id="writer" type="text" name="writer" placeholder="작성자 (실명)"><br>
            <input id="phone" type="text" name="phone" placeholder="전화번호 뒤 4자리"><br>
            <input id="title" type="text" name="title" placeholder="제목"><br>
            <textarea id="content" type="text" name="body" placeholder="수고한 멘토들에게 따뜻한 한마디를 작성해주세요 :)"></textarea><br>
            <button id="submit_button" type="submit">제출</button><br><br><br>
        </form>
    </div>

{% endif %}

{% endblock %}

main/templates/main/pwd.html
<!-- 감사한 여러분께 -->
{% extends 'base.html' %}

{% load static %}

{% block content %}

<body>
    <img id="foryou" src="https://ifh.cc/g/VVDrpT.jpg">
    <div class="check">
        <div class="container">
            <input type="password" placeholder="Password" id="password_2" class="account">
            <br>
            <button id="check_button" class="account">확인</button><br><br><br>
        </div>
    </div>   
    <script type="text/javascript">
            const password = document.getElementById('password_2')
            const login = document.getElementById('check_button')

            login.addEventListener('click', () => {
                if (password.value == 'welcome12th') {
                        location.href="/thanks"
                    }
                else {
                    alert('비밀번호를 다시 입력해주세요!')
                }
            })
    </script>
</body>

{% endblock %}

main/templates/main/pwd_2.html
<!-- 수고한 멘토에게 -->
{% extends 'base.html' %}

{% load static %}

{% block content %}

<body>
    <div style="margin: auto;">
        <img id="toMentors" src="https://ifh.cc/g/aoGnvM.jpg">
    </div>
    <div class="check">
        <div class="container">
            <input type="password" placeholder="Password" id="password_2" class="account">
            <br>
            <button id="check_button" class="account">확인</button><br><br><br>
        </div>
    </div>   
    <script type="text/javascript">
            const password = document.getElementById('password_2')
            const login = document.getElementById('check_button')

            check_button.addEventListener('click', () => {
                if (password.value == '0000') {
                        location.href="/new"
                    }
                else {
                    alert('비밀번호를 다시 입력해주세요!')
                }
            })
    </script>
</body>

{% endblock %}

main/templates/main/pwd_3.html
<!-- 수고한 멘토에게 -->
{% extends 'base.html' %}

{% load static %}

{% block content %}

<body>
    <div style="margin: auto;">
        <img id="toMentors" src="https://ifh.cc/g/hwMnNK.jpg">
    </div>
    <div class="check">
        <div class="container">
            <input type="password" placeholder="Password" id="password_2" class="account">
            <br>
            <button id="check_button" class="account">확인</button><br><br><br>
        </div>
    </div>   
    <script type="text/javascript">
            const password = document.getElementById('password_2')
            const login = document.getElementById('check_button')

            check_button.addEventListener('click', () => {
                if (password.value == 'ako2023') {
                        location.href="/dff"
                    }
                else {
                    alert('비밀번호를 다시 입력해주세요!')
                }
            })
    </script>
</body>

{% endblock %}

main/templates/main/recruit.html
{% extends 'base.html' %}

{% block content %}
<div class="recruit">
    <img id="poster_1" src="https://ifh.cc/g/Drt0nV.jpg">
    <img id="poster_2" src="https://ifh.cc/g/pR32LC.jpg">
    <br>
    <button type="button" id="ipsi" onclick="window.open('https://ipsi.dongguk.edu/admission/html/main/main.asp')">입학처 홈페이지</button>
    <button type="button" id="recruit_insta" onclick="window.open('https://www.instagram.com/dongguk_dreamer/')">@dongguk_dreamer</button>
    <br>
    <a id="recruit_ment">버튼을 누르면 페이지가 해당 페이지로 이동해요!</a>
</div>

{% endblock %}

main/templates/main/thanks.html
{% extends 'base.html' %}

{% block content %}
<div class="thanks_all">
    <img id="yoons_thanks" src="https://ifh.cc/g/DacvP2.jpg">
    <img id="kim_thanks" src="https://ifh.cc/g/AfPlRm.jpg">
    <img id="oh_thanks" src="https://ifh.cc/g/z3vcDO.jpg">
    <img id="yu_thanks" src="https://ifh.cc/g/y2GMlL.jpg">
    <br><br>
</div>  

{% endblock %}